apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-agent
spec:
  project: sysdig
  source:
    repoURL: https://github.com/sysdiglabs/charts
    chart: sysdig-deploy
    targetRevision: "1.66.8"  # Specify the desired chart version
    helm:
      valueFiles:
        - apps/sysdig-agent/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sysdig-agent
  syncPolicy:
    manual: {}
